# Generated by Django 3.0.8 on 2020-09-21 21:24

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to='files', validators=[files.models.valid_extension]),
        ),
    ]
